project_id = "xllpedrhhzoljkfvkgef"

[functions.market-forecast]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.predict-yield]
verify_jwt = false

[functions.sync-agmarknet]
verify_jwt = false
