project_id = "xllpedrhhzoljkfvkgef"

[functions.market-forecast]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.predict-yield]
verify_jwt = false

[functions.sync-agmarknet]
verify_jwt = true

[functions.etl-pipeline]
verify_jwt = true

[functions.ml-forecast]
verify_jwt = false

[functions.ml-monitor]
verify_jwt = true

[functions.farm-finance]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.google-tts]
verify_jwt = false
